Añadiendo dependencia de jasperreports y cambiando el banner de la app
rolandopalermo/veronica pull request #40
Opened 2020-05-09 22:24 UTC by israteneda

Añadí la dependencia `jasperreports-fonts` para que los pdf de los documentos se muestren con negrilla, ya que sin esta dependencia no se imprimían las negrillas. Además agregue un banner para que se muestre el nombre del proyecto en consola al correrlo.

2020-05-10 04:50 UTC, rolandopalermo requested changes

2020-05-10 04:50 UTC, rolandopalermo commented on app/src/main/resources/banner.txt
> +${AnsiColor.GREEN}
Dado un tema de compatibilidad con otros proyectos, este archivo deberá ser removido del pull request antes de proceder con el merge

2020-05-10 22:08 UTC, israteneda commented on app/src/main/resources/banner.txt
> +${AnsiColor.GREEN}
Ok @rolandopalermo el archivo ha sido removido

2020-05-12 15:34 UTC, rolandopalermo approved these changes

2020-05-12 15:34 UTC, merged